// Image metadata with positioning attributes
export const IMAGE_DATA = [
  // {
  //   path: "/three_images/05.jpg",
  //   digitalness: 0.3,
  //   physicalness: 0.8,
  //   productness: 0.7,
  //   experienceness: 0.4,
  //   project: "Physical Product",
  //   name: "Image 1",
  //   description: "Physical product prototype showcasing material exploration and fabrication techniques.",
  // },
  // {
  //   path: "/three_images/07_BEACON_FRONT (1).png",
  //   digitalness: 0.4,
  //   physicalness: 0.9,
  //   productness: 0.8,
  //   experienceness: 0.3,
  //   project: "Beacon",
  //   name: "Image 2",
  //   description: "Beacon project front view demonstrating physical product design and LED integration.",
  // },
  // {
  //   path: "/three_images/4ccc6ebb-fad8-45cd-a469-881146f4d-41.jpeg",
  //   digitalness: 0.5,
  //   physicalness: 0.6,
  //   productness: 0.5,
  //   experienceness: 0.6,
  //   project: "Mixed",
  //   name: "Image 3",
  //   description: "Mixed media project exploring the intersection of digital and physical design practices.",
  // },
  // {
  //   path: "/three_images/DSC02213-2.jpg",
  //   digitalness: 0.2,
  //   physicalness: 0.9,
  //   productness: 0.6,
  //   experienceness: 0.5,
  //   project: "Physical",
  //   name: "Image 4",
  //   description: "Detail shot of physical fabrication work highlighting materiality and craftsmanship.",
  // },
  // {
  //   path: "/three_images/DSCF1215.jpg",
  //   digitalness: 0.3,
  //   physicalness: 0.8,
  //   productness: 0.7,
  //   experienceness: 0.4,
  //   project: "Physical Product",
  //   name: "Image 5",
  //   description: "Product photography showcasing industrial design and manufacturing process.",
  // },
  // // {
  // //   path: "/three_images/IMG_7810.jpeg",
  // //   digitalness: 0.4,
  // //   physicalness: 0.7,
  // //   productness: 0.6,
  // //   experienceness: 0.5,
  // //   project: "Photography",
  // //   name: "Image 6",
  // //   description: "Documentary photography capturing the studio's design and research process.",
  // // },
  // // {
  // //   path: "/three_images/MotionPicturesFigure1.jpg",
  // //   digitalness: 0.8,
  // //   physicalness: 0.3,
  // //   productness: 0.2,
  // //   experienceness: 0.9,
  // //   project: "Motion Pictures",
  // //   name: "Image 7",
  // //   description: "Motion Pictures research project exploring temporal and spatial interaction design.",
  // // },
  // {
  //   path: "/three_images/MotionPicturesFigure3.jpg",
  //   digitalness: 0.8,
  //   physicalness: 0.3,
  //   productness: 0.2,
  //   experienceness: 0.9,
  //   project: "Motion Pictures",
  //   name: "Image 8",
  //   description: "Motion Pictures project detail showing interface design and user experience flow.",
  // },
  // {
  //   path: "/three_images/pasted-movie-6.png",
  //   digitalness: 0.9,
  //   physicalness: 0.2,
  //   productness: 0.3,
  //   experienceness: 0.8,
  //   project: "Digital Interface",
  //   name: "Image 9",
  //   description: "Digital interface design showcasing computational design and interaction patterns.",
  // },
  // {
  //   path: "/three_images/pasted-movie-7.png",
  //   digitalness: 0.9,
  //   physicalness: 0.2,
  //   productness: 0.3,
  //   experienceness: 0.8,
  //   project: "Digital Interface",
  //   name: "Image 10",
  //   description: "Screen-based interface exploration demonstrating digital experience design.",
  // },
  // {
  //   path: "/three_images/pasted-movie-8.png",
  //   digitalness: 0.9,
  //   physicalness: 0.2,
  //   productness: 0.3,
  //   experienceness: 0.8,
  //   project: "Digital Interface",
  //   name: "Image 11",
  //   description: "Interactive digital prototype showing user interface and visual design system.",
  // },
  // {
  //   path: "/three_images/pasted-movie-10.png",
  //   digitalness: 0.9,
  //   physicalness: 0.2,
  //   productness: 0.3,
  //   experienceness: 0.8,
  //   project: "Digital Interface",
  //   name: "Image 12",
  //   description: "Digital interface mockup highlighting information architecture and visual hierarchy.",
  // },
  {
    path: "/three_images/pasted-movie-12.png",
    digitalness: 1,
    physicalness: 1,
    productness: 1,
    experienceness: .5,
    project: "Pixelframe",
    name: "Pixelframe",
    description: "Scanning concrete elements in AR.",
    year: 2025,
  },
  {
    path: "/three_images/IMG_4980.webp",
    digitalness: .5,
    physicalness: 1,
    productness: .7,
    experienceness: .7,
    project: "Pixelframe",
    name: "Pixelframe",
    description: "User looks at 3D scan of building proposal.",
    year: 2025,
    scale: 1.7,
  },
  {
    path: "/three_images/Spolia_Beam_DEMO2025_2.webp",
    digitalness: .8,
    physicalness: .7,
    productness: .3,
    experienceness: .9,
    project: "Beacons",
    name: "Beacons",
    description: "Beacon Octo renders biota data from the deep sea.",
    year: 2025,
    scale: 1.7,
  },
  {
    path: "/three_images/symlink_1 2.webp",
    digitalness: .8,
    physicalness: .3,
    productness: .2,
    experienceness: .5,
    project: "Symlink",
    name: "Symlink",
    description: "Output from Symlink AI system.",
    year: 2025,
    scale: .9,
  },
  // {
  //   path: "/three_images/Vercoe, Garrett_1.png",
  //   digitalness: 0.5,
  //   physicalness: 0.5,
  //   productness: 0.4,
  //   experienceness: 0.6,
  //   project: "Portrait",
  //   name: "Image 14",
  //   description: "Studio portrait capturing the intersection of design practice and personal vision.",
  // },
  // // {
  // //   path: "/three_images/wood-proto-fabrics-large.jpeg",
  // //   digitalness: 1,
  // //   physicalness: 1,
  // //   productness: 1,
  // //   experienceness: 1,
  // //   project: "Pixelframe",
  // //   name: "RFID Scanning Tech",
  // //   description: "Material research exploring wood and fabric prototypes for product design.",
  // // },
  // // {
  // //   path: "/three_images/three-02.webp",
  // //   digitalness: 0.1,
  // //   physicalness: 1,
  // //   productness: 0.9,
  // //   experienceness: 0.1,
  // //   project: "Studio",
  // //   name: "CNC Install",
  // //   description: "Studio workspace documentation showing design tools and creative process.",
  // //   year: 2018,
  // // },
  // {
  //   path: "/three_images/three-03.webp",
  //   digitalness: 0.6,
  //   physicalness: 0.9,
  //   productness: 1,
  //   experienceness: 0,
  //   project: "Studio",
  //   name: "Discussing Mixed Reality Implementation",
  //   description: "Behind the scenes of physical prototyping and fabrication in the studio.",
  //   year: 2020,
  // },
  // {
  //   path: "/three_images/three-04.webp",
  //   digitalness: 0.2,
  //   physicalness: 0.9,
  //   productness: 0.5,
  //   experienceness: 0.8,
  //   project: "Beacons",
  //   name: "Raspberry Pi Detail",
  //   description: "Material experimentation and hands-on making processes in the studio environment.",
  // },
  // {
  //   path: "/three_images/three-05.webp",
  //   digitalness: 0.3,
  //   physicalness: 0.9,
  //   productness: 0.1,
  //   experienceness: 0.9,
  //   project: "Beacons",
  //   name: "Beacons Trio",
  //   description: "Studio practice documentation highlighting iterative design and testing methods.",
  //   year: 2025,
  // },
  // {
  //   path: "/three_images/three-06.webp",
  //   digitalness: 0.2,
  //   physicalness: 0.9,
  //   productness: 0.7,
  //   experienceness: 0.4,
  //   project: "Studio",
  //   name: "Image 20",
  //   description: "Workshop detail showing tools, materials, and craftsmanship in action.",
  // },
  // {
  //   path: "/three_images/three-07.webp",
  //   digitalness: 0.3,
  //   physicalness: 0.8,
  //   productness: 0.7,
  //   experienceness: 0.4,
  //   project: "Studio",
  //   name: "Image 21",
  //   description: "Studio photography capturing the intersection of making and thinking.",
  // },
  // {
  //   path: "/three_images/three-08.webp",
  //   digitalness: 0.2,
  //   physicalness: 0.9,
  //   productness: 0.7,
  //   experienceness: 0.4,
  //   project: "Studio",
  //   name: "Image 22",
  //   description: "Physical construction and assembly process documented in the studio space.",
  // },
  {
    path: "/three_images/three-09.webp",
    digitalness: 0,
    physicalness: .7,
    productness: 0.7,
    experienceness: 0,
    project: "Symlink",
    name: "Abstracts",
    description: "Symlink recent publication in Cambridge Biotechnology Design Journal.",
    year: 2025,
  },
  // {
  //   path: "/three_images/three-10.webp",
  //   digitalness: 0.8,
  //   physicalness: 0.3,
  //   productness: 0.2,
  //   experienceness: 0.9,
  //   project: "Digital Experience",
  //   name: "Image 24",
  //   description: "Immersive digital experience showcasing interactive design and user engagement.",
  // },
  // {
  //   path: "/three_images/three-11.webp",
  //   digitalness: 0.4,
  //   physicalness: 0.8,
  //   productness: 0.3,
  //   experienceness: 0.8,
  //   project: "Beacons",
  //   name: "Beacons Prototype",
  //   description: "Screen interface design demonstrating responsive layouts and interaction design.",
  //   year: 2025,
  //   hide: true,
  // },
  // {
  //   path: "/three_images/three-12.webp",
  //   digitalness: 0.1,
  //   physicalness: 0.8,
  //   productness: 0.7,
  //   experienceness: 0.5,
  //   project: "Beacons",
  //   name: "Testing Hardware",
  //   description: "Tangible object design focusing on form, function, and user interaction.",
  //   year: 2025,
  // },
  // {
  //   path: "/three_images/three-13.webp",
  //   digitalness: 0.4,
  //   physicalness: 0.7,
  //   productness: 0.6,
  //   experienceness: 0.5,
  //   project: "Mixed",
  //   name: "Image 27",
  //   description: "Hybrid project bridging physical and digital realms through integrated design.",
  // },
  // {
  //   path: "/three_images/three-14.webp",
  //   digitalness: 0.5,
  //   physicalness: 1,
  //   productness: 0.2,
  //   experienceness: 1,
  //   project: "Digital Experience",
  //   name: "Social Signals",
  //   description: "Interactive experience design exploring new modes of engagement and participation.",
  //   year: 2023,
  // },
  // {
  //   path: "/three_images/three-15.webp",
  //   digitalness: 0.8,
  //   physicalness: 0.2,
  //   productness: 0.1,
  //   experienceness: 0.9,
  //   project: "Digital",
  //   name: "Custom GAN",
  //   description: "Digital media work combining graphics, motion, and interaction design principles.",
  //   year: 2021,
  // },
  // {
  //   path: "/three_images/three-16.webp",
  //   digitalness: 1,
  //   physicalness: 0,
  //   productness: 0.7,
  //   experienceness: 0,
  //   project: "AI Generative",
  //   name: "Grasshopper Detail",
  //   description: "Cross-disciplinary project integrating multiple design methodologies and outputs.",
  //   year: 2024,
  // },
  // {
  //   path: "/three_images/three-17.webp",
  //   digitalness: 1,
  //   physicalness: 0,
  //   productness: 0.3,
  //   experienceness: 0.3,
  //   project: "Beacons",
  //   name: "Deep Sea Data Projection",
  //   description: "Software interface and digital tools designed for creative workflows.",
  //   year: 2024,
  //    hide: true,
  // },
  // {
  //   path: "/three_images/three-18.webp",
  //   digitalness: 0.6,
  //   physicalness: 0.8,
  //   productness: 0.1,
  //   experienceness: 0.9,
  //   project: "Digital Experience",
  //   name: "Beacons Detail Up Close",
  //   description: "Experiential digital installation merging technology and human interaction.",
  //   year: 2025,
  // },
  // {
  //   path: "/three_images/three-19.webp",
  //   digitalness: .7,
  //   physicalness: 0,
  //   productness: 0.5,
  //   experienceness: 0.2,
  //   project: "Engelbart",
  //   name: "Engelbart Visualization",
  //   description: "Web-based interface design featuring dynamic content and visual storytelling.",
  //   year: 2020,
  //   hide: true,
  // },
  // {
  //   path: "/three_images/three-20.webp",
  //   digitalness: 0.8,
  //   physicalness: 0.2,
  //   productness: 0,
  //   experienceness: 0.8,
  //   project: "Beacons",
  //   name: "Beacons Sketch",
  //   description: "Digital platform design emphasizing usability and aesthetic coherence.",
  //   year: 2025,
  // },
  // {
  //   path: "/three_images/three-21.webp",
  //   digitalness: 0.3,
  //   physicalness: 1,
  //   productness: 1,
  //   experienceness: 0.5,
  //   project: "Digital",
  //   name: "CNC Wood",
  //   description: "Application interface showcasing user-centered design and visual clarity.",
  //   year: 2018,
  // },
  // {
  //   path: "/three_images/three-22.webp",
  //   digitalness: 0.8,
  //   physicalness: 0.2,
  //   productness: 0,
  //   experienceness: 0.6,
  //   project: "Digital",
  //   name: "Computer Vision 2",
  //   description: "Digital product design balancing functionality with expressive visual language.",
  //   year: 2020,
  // },
  // {
  //   path: "/three_images/three-23.webp",
  //   digitalness: 0.7,
  //   physicalness: 0.3,
  //   productness: 0.3,
  //   experienceness: 0.7,
  //   project: "Digital Experience",
  //   name: "Computer Vision",
  //   description: "Experiential design project creating memorable and engaging digital moments.",
  //   year: 2020
  // },
  // {
  //   path: "/three_images/three-24.webp",
  //   digitalness: 0.1,
  //   physicalness: 0.8,
  //   productness: 0.3,
  //   experienceness: 0.8,
  //   project: "Digital",
  //   name: "Eric Sautering a Speaker",
  //   description: "Digital design exploration testing new patterns and interaction paradigms.",
  //   year: 2025
  // },
  // {
  //   path: "/three_images/three-25.webp",
  //   digitalness: 0.2,
  //   physicalness: 1,
  //   productness: 0,
  //   experienceness: 1,
  //   project: "Wood Proto",
  //   name: "Detail of Material Bind",
  //   description: "Material sample and texture research informing physical product development.",
  //   year: 2019
  // },
];

// Ensure default scale metadata on every image (scale: 1)
IMAGE_DATA.forEach((img) => {
  if (img.scale === undefined) {
    img.scale = 1;
  }
  // Back-compat: if legacy `size` exists but `scale` not set, use it
  if (img.scale === 1 && img.size !== undefined) {
    img.scale = img.size;
  }
});

// Legacy: Extract just paths for backwards compatibility
export const IMAGE_PATHS = IMAGE_DATA.map((img) => img.path);

// Layout configuration
export const LAYOUT_CONFIG = {
  radius: 4, // Reduced radius for tighter circle with more overlap
  spacing: 2.5, // Reduced spacing for more overlap
};

// Animation configuration
export const ANIMATION_CONFIG = {
  imageScaleDuration: 400, // Base duration for image scale animation
  imageScaleDelay: 20, // Delay increment between images
  cursorOffset: 0.64, // Max cursor offset for images
};

// Animation phases and timing
export const ANIMATION_PHASES = {
  CIRCULAR: "circular",
  SCATTERED: "scattered",
};

export const PHASE_TIMING = {
  initialDelay: 2000, // Wait 2 seconds after initial load
  transitionDelay: 1000, // Wait 1 second before switching to scattered
};

// Camera configuration
export const CAMERA_CONFIG = {
  position: [0, 0, 20],
  fov: 60,
};

// Scene configuration
export const SCENE_CONFIG = {
  backgroundColor: "#302C1E",
};
